export const HTTP_STATUS: {
  OK: number
  CREATED: number
  BAD_REQUEST: number
  UNAUTHORIZED: number
  FORBIDDEN: number
  NOT_FOUND: number
  CONFLICT: number
  UNPROCESSABLE_ENTITY: number
  INTERNAL_SERVER_ERROR: number
} = {
  OK: 200,
  CREATED: 201,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  CONFLICT: 409,
  UNPROCESSABLE_ENTITY: 422,
  INTERNAL_SERVER_ERROR: 500
} as const
